### ISSUE TITLE
iPad: webkit-media-controls may persist

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1065]
This happens very rarely. The only scenario where can observe it are some cold starts of encrypted HLS, like at https://flowplayer.blacktrash.org/hls-crypt/

![persistent-webkit-playbutton](https://cloud.githubusercontent.com/assets/168338/19409698/12283c34-92da-11e6-8e72-683410c7ea55.png)

The play button goes away after a pause or seek, but it's still annoying.

Presumably happens because of a minimal interval where the device sees the video tag before flowplayer takes over during key retrieval.

Fix via CSS:

``` css
.flowplayer video.fp-engine::-webkit-media-controls {
  display: none !important;
}
```

This also looks sufficient, but makes not differences (also not re: ad plugins, see below):

``` css
.flowplayer video.fp-engine::-webkit-media-controls-start-playback-button {
  display: none !important;
}
```

The only debatable scenario I see is in conjunction with the advert plugins on iPhone; the paused ad player does not show the native play button anymore:

![vast-iphone-no-webkit-controls](https://cloud.githubusercontent.com/assets/168338/19409726/c55e840c-92da-11e6-90ae-297b9c55d944.png)

Arguably this is not a drawback, the tiny space is less cluttered, and to continue the user would instinctively tap the blank area.
Alternative: show a play-button image, but that is clumsy.

I haven't experimented with explicit `controls="false"` video tag settings. There might be other scenarios where iOS still tries to re-add the controls, so CSS seems easy and reliable.
