### ISSUE TITLE
fp-waiting loading animation only visible on hover

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1218]
The loading animation should be visible independently of whether the user hovers over the player area or not.
As this can be fixed by:
```css
.flowplayer.is-loading .fp-waiting, .flowplayer.is-seeking .fp-waiting {
  display: block !important; /* !important flag added
}
```
this looks a lot like a simple oversight.

See: https://flowplayer.com/forum/#!/skinning_css:player-doesnt-show-waiting
