### ISSUE TITLE
Fullscreen: hide cursor on mouseout

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1223]
The cursor can be felt as very distracting in fullscreen; see e.g. https://flowplayer.com/forum/#!/setup:how-hidden-cursor-in-fullsc

I propose:
```css
.flowplayer.is-fullscreen.is-mouseout .fp-ui {
  cursor: none;
}
```
which seems to work fine in tests so far.

**Comment by blacktrash** [comment]
Or, as controls are shown in paused state, for consistency:
```css
.flowplayer.is-fullscreen.is-mouseout.is-playing .fp-ui {
  cursor: none;
}
```
