### ISSUE TITLE
Player overflows its block

### ISSUE THREAD

**Issue by artpolikarpov** [flowplayer/flowplayer#203]
When I trying to make a fullwindow (fullbrowser) player I get overflow problem.

Style I use to fill the window:

``` css
html,
body,
.flowplayer {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
}
```

I don’t want any scrollbars at all, but I get a vertical one, because player’s UI overflows its block. Live example:

http://artpolikarpov.ru/dialogues/flowplayer/oversized/index.html

I've fixed it with following:

``` css
.flowplayer {
  overflow: hidden;
  vertical-align: top;
}
.flowplayer.is-mouseout .fp-controls {
  height: 3px;
}
```

http://artpolikarpov.ru/dialogues/flowplayer/fitted/index.html

---

I need fullwindow player to append it through iframe with unknown width and height, like YouTube or Vimeo player.
