### ISSUE TITLE
splash state: player should not be in paused state

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#312]
A player which is not loaded cannot be paused, so logically it doesn't make sense.

In practice: one cannot do for instance:

``` css
.is-paused.flowplayer .fp-ui {
  background-image: none;
}
```

to hide the on-screen play button in paused - but not in splash! - state.
