### ISSUE TITLE
CSS issue on touch devices

### ISSUE THREAD

**Issue by dvLden** [flowplayer/flowplayer#864]
I am not sure if you guys noticed this, but there is one really ugly CSS issue for touch devices if using an framework or if you are applying border-box to all your elements in your CSS.

So when this is applied to all elements or when Bootstrap is used for example...
```css
*, :after, :before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

You will get following look on player control / seek bar:
![Flowplayer Default](http://i.imgur.com/aF28Qvs.png)
![Flowplayer Default](http://i.imgur.com/JJABDTM.png)

So just slight changes applied will resolve it...
```css
.minimalist.is-touch.is-mouseover .fp-progress:after {
  height: 18px;
  width: 18px;
  top: -4px;
  right: -10px;
  border: 5px solid rgba(255, 255, 255, .65);
  -webkit-box-shadow: 1px 0 4px rgba(0, 0, 0, .5);
  -moz-box-shadow: 1px 0 4px rgba(0, 0, 0, .5);
  box-shadow: 1px 0 4px rgba(0, 0, 0, .5);
}

.minimalist.is-touch.is-mouseover .fp-timeline.is-dragging .fp-progress:after {
  border: 10px solid #fff;
  -webkit-border-radius: 20px;
  -moz-border-radius: 20px;
  border-radius: 20px;
  -webkit-transition: inherit;
  -moz-transition: inherit;
  transition: inherit;
  top: -5px;
  right: -15px;
}
```

Now it will look like on official's Flowplayer's demos. Well I just thought to report it as issue, because I am sure many people use an CSS "framework".
